/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ConversationMember } from './conversation-member';
// May contain unused imports in some cases
// @ts-ignore
import { ConversationType } from './conversation-type';
// May contain unused imports in some cases
// @ts-ignore
import { Message } from './message';

/**
 * 
 * @export
 * @interface Conversation
 */
export interface Conversation {
    /**
     * 
     * @type {Array<object>}
     * @memberof Conversation
     */
    'domainEvents': Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    'lastModified': string;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    'lastModifiedBy'?: string | null;
    /**
     * 
     * @type {ConversationType}
     * @memberof Conversation
     */
    'type': ConversationType;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    'conversationId': string;
    /**
     * 
     * @type {Array<ConversationMember>}
     * @memberof Conversation
     */
    'members': Array<ConversationMember>;
    /**
     * 
     * @type {Array<Message>}
     * @memberof Conversation
     */
    'messages': Array<Message>;
}



