/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConversationMember
 */
export interface ConversationMember {
    /**
     * 
     * @type {Array<object>}
     * @memberof ConversationMember
     */
    'domainEvents': Array<object>;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    'lastModified': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    'lastModifiedBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    'conversationId': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof ConversationMember
     */
    'defaultEmoji': string;
    /**
     * 
     * @type {boolean}
     * @memberof ConversationMember
     */
    'isHidden': boolean;
    /**
     * 
     * @type {number}
     * @memberof ConversationMember
     */
    'receivedToId': number;
    /**
     * 
     * @type {number}
     * @memberof ConversationMember
     */
    'seenToId': number;
    /**
     * 
     * @type {number}
     * @memberof ConversationMember
     */
    'loadFromId': number;
}

