/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FileMetadata
 */
export interface FileMetadata {
    /**
     * 
     * @type {string}
     * @memberof FileMetadata
     */
    'path': string;
    /**
     * 
     * @type {string}
     * @memberof FileMetadata
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof FileMetadata
     */
    'size': number;
    /**
     * 
     * @type {string}
     * @memberof FileMetadata
     */
    'contentType': string;
    /**
     * 
     * @type {string}
     * @memberof FileMetadata
     */
    'createdDate': string;
}

