/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface FriendRequest
 */
export interface FriendRequest {
    /**
     * 
     * @type {string}
     * @memberof FriendRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof FriendRequest
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof FriendRequest
     */
    'sendTime': string;
}

