/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupSetting
 */
export interface GroupSetting {
    /**
     * 
     * @type {boolean}
     * @memberof GroupSetting
     */
    'allowChangeGName': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupSetting
     */
    'allowSendGInvitation': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupSetting
     */
    'membershipApproval': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupSetting
     */
    'readRecentMessage': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof GroupSetting
     */
    'joinGroupByLink': boolean;
    /**
     * 
     * @type {string}
     * @memberof GroupSetting
     */
    'groupCode': string;
}

