/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { MemberRole } from './member-role';

/**
 * 
 * @export
 * @interface GroupMember
 */
export interface GroupMember {
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    'groupId': string;
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    'userId': string;
    /**
     * 
     * @type {MemberRole}
     * @memberof GroupMember
     */
    'role': MemberRole;
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    'joinDate': string;
    /**
     * 
     * @type {string}
     * @memberof GroupMember
     */
    'joinBy'?: string | null;
}



