/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FileMetadata } from './file-metadata';
// May contain unused imports in some cases
// @ts-ignore
import { MessageStatus } from './message-status';

/**
 * 
 * @export
 * @interface Message
 */
export interface Message {
    /**
     * 
     * @type {Array<object>}
     * @memberof Message
     */
    'domainEvents': Array<object>;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'lastModified': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'lastModifiedBy'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof Message
     */
    'isDeleted': boolean;
    /**
     * 
     * @type {number}
     * @memberof Message
     */
    'messageId': number;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'conversationId': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'fromUserId': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'sendTime': string;
    /**
     * 
     * @type {string}
     * @memberof Message
     */
    'text': string;
    /**
     * 
     * @type {MessageStatus}
     * @memberof Message
     */
    'status': MessageStatus;
    /**
     * 
     * @type {Array<FileMetadata>}
     * @memberof Message
     */
    'files': Array<FileMetadata>;
}



