/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Gender } from './gender';

/**
 * 
 * @export
 * @interface RegisterRequest
 */
export interface RegisterRequest {
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    'countryCode': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    'phoneNumber': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    'birthday': string;
    /**
     * 
     * @type {Gender}
     * @memberof RegisterRequest
     */
    'gender': Gender;
    /**
     * 
     * @type {string}
     * @memberof RegisterRequest
     */
    'password': string;
}



