/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { PhoneNumber } from './phone-number';

/**
 * 
 * @export
 * @interface SystemInfoOptions
 */
export interface SystemInfoOptions {
    /**
     * 
     * @type {string}
     * @memberof SystemInfoOptions
     */
    'version': string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoOptions
     */
    'appName': string;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoOptions
     */
    'email': string;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof SystemInfoOptions
     */
    'adminPhone': PhoneNumber;
    /**
     * 
     * @type {string}
     * @memberof SystemInfoOptions
     */
    'globalGroupCode': string;
    /**
     * 
     * @type {number}
     * @memberof SystemInfoOptions
     */
    'maxFileSize': number;
    /**
     * 
     * @type {number}
     * @memberof SystemInfoOptions
     */
    'maxFileCountPerMessage': number;
}

