/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { FriendRequest } from './friend-request';
// May contain unused imports in some cases
// @ts-ignore
import { Gender } from './gender';
// May contain unused imports in some cases
// @ts-ignore
import { PhoneNumber } from './phone-number';

/**
 * 
 * @export
 * @interface UserInfo
 */
export interface UserInfo {
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'userId': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserInfo
     */
    'avatar': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'name': string;
    /**
     * 
     * @type {Gender}
     * @memberof UserInfo
     */
    'gender': Gender;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'birthday': string;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'alias'?: string | null;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof UserInfo
     */
    'phone'?: PhoneNumber | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserInfo
     */
    'isFriend': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserInfo
     */
    'conversationId'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserInfo
     */
    'blocked': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof UserInfo
     */
    'beBlocked': boolean;
    /**
     * 
     * @type {FriendRequest}
     * @memberof UserInfo
     */
    'requestOfUser'?: FriendRequest | null;
    /**
     * 
     * @type {FriendRequest}
     * @memberof UserInfo
     */
    'requestOfFriend'?: FriendRequest | null;
}



