/* tslint:disable */
/* eslint-disable */
/**
 * WebChat.WebAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Gender } from './gender';
// May contain unused imports in some cases
// @ts-ignore
import { PhoneNumber } from './phone-number';

/**
 * 
 * @export
 * @interface User
 */
export interface User {
    /**
     * 
     * @type {Array<object>}
     * @memberof User
     */
    'domainEvents': Array<object>;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'created': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'createdBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastModified': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'lastModifiedBy'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'userId': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'avatarPath'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'birthday': string;
    /**
     * 
     * @type {Gender}
     * @memberof User
     */
    'gender': Gender;
    /**
     * 
     * @type {PhoneNumber}
     * @memberof User
     */
    'phoneNumber': PhoneNumber;
    /**
     * 
     * @type {string}
     * @memberof User
     */
    'conversationId': string;
}



